"""
Admin Panel Routes - Super Admin Dashboard & Management
Provides /admin/dashboard, /admin/tenants, /admin/users, /admin/usage
"""

from flask import Blueprint, render_template, request, redirect, url_for, flash, jsonify
from flask_login import login_required, current_user
from datetime import datetime, timedelta

from web.models import db, Tenant, User, Server, AgentKey, Metric, SystemAlert, AuditLog
from web.utils import require_superadmin

admin_bp = Blueprint('admin', __name__, url_prefix='/admin')


@admin_bp.route('/dashboard')
@login_required
@require_superadmin
def admin_dashboard():
    """Super Admin overview dashboard"""
    tenants = Tenant.query.all()
    total_users = User.query.count()
    total_servers = Server.query.count()
    total_keys = AgentKey.query.filter_by(is_active=True).count()
    active_alerts = SystemAlert.query.filter_by(is_active=True).count()

    online_servers = sum(1 for s in Server.query.all() if s.is_online)

    # Recent audit logs
    recent_logs = AuditLog.query.order_by(AuditLog.timestamp.desc()).limit(20).all()

    # Per-tenant stats
    tenant_stats = []
    for t in tenants:
        server_count = Server.query.filter_by(tenant_id=t.id).count()
        user_count = User.query.filter_by(tenant_id=t.id).count()
        key_count = AgentKey.query.filter_by(tenant_id=t.id, is_active=True).count()
        tenant_stats.append({
            'tenant': t,
            'servers': server_count,
            'users': user_count,
            'keys': key_count
        })

    return render_template('admin/dashboard.html',
                           tenants=tenants, tenant_stats=tenant_stats,
                           total_users=total_users, total_servers=total_servers,
                           total_keys=total_keys, active_alerts=active_alerts,
                           online_servers=online_servers, recent_logs=recent_logs)


@admin_bp.route('/tenants')
@login_required
@require_superadmin
def admin_tenants():
    """Manage all tenants"""
    tenants = Tenant.query.all()
    tenant_data = []
    
    for t in tenants:
        tenant_data.append({
            'tenant': t,
            'servers': Server.query.filter_by(tenant_id=t.id).count(),
            'users': User.query.filter_by(tenant_id=t.id).count(),
            'keys': AgentKey.query.filter_by(tenant_id=t.id, is_active=True).count(),
            'azure': t.azure_registered or False,
            'azure_org': None
        })
    return render_template('admin/tenants.html', tenant_data=tenant_data)


@admin_bp.route('/tenants/create', methods=['POST'])
@login_required
@require_superadmin
def admin_create_tenant():
    """Create a new tenant"""
    name = request.form.get('name', '').strip()
    if not name:
        flash('Tenant name is required', 'danger')
        return redirect(url_for('admin.admin_tenants'))

    if Tenant.query.filter_by(name=name).first():
        flash('Tenant name already exists', 'danger')
        return redirect(url_for('admin.admin_tenants'))

    t = Tenant(name=name)
    db.session.add(t)
    db.session.commit()

    # Auto-generate an agent key for the new tenant
    key = AgentKey(tenant_id=t.id, key_name=f'{name} Default Key', description='Auto-generated on tenant creation')
    db.session.add(key)
    db.session.commit()

    flash(f'Tenant "{name}" created with agent key: {key.key[:16]}...', 'success')
    return redirect(url_for('admin.admin_tenants'))


@admin_bp.route('/tenants/<int:tenant_id>/delete', methods=['POST'])
@login_required
@require_superadmin
def admin_delete_tenant(tenant_id):
    """Delete a tenant and all related data"""
    t = db.session.get(Tenant, tenant_id)
    if not t:
        flash('Tenant not found', 'danger')
        return redirect(url_for('admin.admin_tenants'))

    # Delete related data
    AgentKey.query.filter_by(tenant_id=t.id).delete()
    User.query.filter_by(tenant_id=t.id).delete()
    servers = Server.query.filter_by(tenant_id=t.id).all()
    for s in servers:
        Metric.query.filter_by(server_id=s.id).delete()
    Server.query.filter_by(tenant_id=t.id).delete()
    db.session.delete(t)
    db.session.commit()

    flash(f'Tenant "{t.name}" and all related data deleted', 'success')
    return redirect(url_for('admin.admin_tenants'))


@admin_bp.route('/tenants/<int:tenant_id>/generate_key', methods=['POST'])
@login_required
@require_superadmin
def admin_generate_key(tenant_id):
    """Generate a new agent key for a tenant"""
    t = db.session.get(Tenant, tenant_id)
    if not t:
        flash('Tenant not found', 'danger')
        return redirect(url_for('admin.admin_tenants'))

    key_name = request.form.get('key_name', f'{t.name} Key')
    key = AgentKey(tenant_id=t.id, key_name=key_name, description='Generated by admin')
    db.session.add(key)
    db.session.commit()

    flash(f'New key generated: {key.key}', 'success')
    return redirect(url_for('admin.admin_tenants'))


@admin_bp.route('/users')
@login_required
@require_superadmin
def admin_users():
    """Manage all users across tenants"""
    users = User.query.all()
    tenants = Tenant.query.all()
    return render_template('admin/users.html', users=users, tenants=tenants)


@admin_bp.route('/users/create', methods=['POST'])
@login_required
@require_superadmin
def admin_create_user():
    """Create a new user"""
    from werkzeug.security import generate_password_hash
    username = request.form.get('username', '').strip()
    password = request.form.get('password', '')
    tenant_id = request.form.get('tenant_id', type=int)
    is_superadmin = request.form.get('is_superadmin') == '1'

    if not username or not password:
        flash('Username and password are required', 'danger')
        return redirect(url_for('admin.admin_users'))

    if User.query.filter_by(username=username).first():
        flash('Username already exists', 'danger')
        return redirect(url_for('admin.admin_users'))

    user = User(
        username=username,
        password=generate_password_hash(password),
        tenant_id=tenant_id,
        is_superadmin=is_superadmin,
        role='super_admin' if is_superadmin else 'tenant_admin'
    )
    db.session.add(user)
    db.session.commit()

    flash(f'User "{username}" created', 'success')
    return redirect(url_for('admin.admin_users'))


@admin_bp.route('/users/<int:user_id>/delete', methods=['POST'])
@login_required
@require_superadmin
def admin_delete_user(user_id):
    """Delete a user"""
    user = db.session.get(User, user_id)
    if not user:
        flash('User not found', 'danger')
        return redirect(url_for('admin.admin_users'))
    if user.id == current_user.id:
        flash('Cannot delete yourself', 'danger')
        return redirect(url_for('admin.admin_users'))

    db.session.delete(user)
    db.session.commit()
    flash(f'User "{user.username}" deleted', 'success')
    return redirect(url_for('admin.admin_users'))


@admin_bp.route('/usage')
@login_required
@require_superadmin
def admin_usage():
    """View tenant usage statistics as JSON"""
    tenants = Tenant.query.all()
    data = []
    for t in tenants:
        server_count = Server.query.filter_by(tenant_id=t.id).count()
        metric_count = Metric.query.join(Server).filter(Server.tenant_id == t.id).count()
        data.append({
            'tenant_id': t.id,
            'tenant_name': t.name,
            'servers': server_count,
            'total_metrics': metric_count
        })
    return jsonify(data)
