"""Add tenant status

Revision ID: cb4ee9860cce
Revises: 0004_add_license_and_productivity_models
Create Date: 2026-05-16 12:32:04.861574

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb4ee9860cce'
down_revision: Union[str, None] = '0004_add_license_and_productivity_models'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_azure_device_tenant'), table_name='azure_device')
    op.drop_index(op.f('idx_azure_device_owner_tenant'), table_name='azure_device_owner')
    op.drop_index(op.f('idx_employee_asset_log_server'), table_name='employee_asset_log')
    op.drop_index(op.f('idx_employee_asset_log_tenant'), table_name='employee_asset_log')
    op.drop_index(op.f('idx_metric_server_timestamp'), table_name='metric')
    op.drop_index(op.f('idx_metric_timestamp'), table_name='metric')
    op.drop_index(op.f('idx_server_agent_installed'), table_name='server')
    op.drop_index(op.f('idx_server_tenant_status'), table_name='server')
    op.drop_index(op.f('idx_system_alert_is_active'), table_name='system_alert')
    op.drop_index(op.f('idx_system_alert_server_active'), table_name='system_alert')
    op.drop_index(op.f('idx_system_discovery_tenant_status'), table_name='system_discovery')
    op.add_column('tenant', sa.Column('status', sa.String(length=50), nullable=True))
    op.create_index(op.f('ix_tenant_status'), 'tenant', ['status'], unique=False)
    op.drop_index(op.f('idx_vm_server'), table_name='vm')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_vm_server'), 'vm', ['server_id'], unique=False)
    op.drop_index(op.f('ix_tenant_status'), table_name='tenant')
    op.drop_column('tenant', 'status')
    op.create_index(op.f('idx_system_discovery_tenant_status'), 'system_discovery', ['tenant_id', 'status'], unique=False)
    op.create_index(op.f('idx_system_alert_server_active'), 'system_alert', ['server_id', 'is_active'], unique=False)
    op.create_index(op.f('idx_system_alert_is_active'), 'system_alert', ['is_active'], unique=False)
    op.create_index(op.f('idx_server_tenant_status'), 'server', ['tenant_id', 'status'], unique=False)
    op.create_index(op.f('idx_server_agent_installed'), 'server', ['agent_installed'], unique=False)
    op.create_index(op.f('idx_metric_timestamp'), 'metric', ['timestamp'], unique=False)
    op.create_index(op.f('idx_metric_server_timestamp'), 'metric', ['server_id', 'timestamp'], unique=False)
    op.create_index(op.f('idx_employee_asset_log_tenant'), 'employee_asset_log', ['tenant_id'], unique=False)
    op.create_index(op.f('idx_employee_asset_log_server'), 'employee_asset_log', ['server_id'], unique=False)
    op.create_index(op.f('idx_azure_device_owner_tenant'), 'azure_device_owner', ['tenant_id'], unique=False)
    op.create_index(op.f('idx_azure_device_tenant'), 'azure_device', ['tenant_id'], unique=False)
    # ### end Alembic commands ###
